version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: nodejs-rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    ports:
      - "15672:15672"
      - "5672:5672"  